"""NearHelp AI — Schemas Registry."""

from app.schemas.ai import (
    ClassificationRequest,
    ClassificationResponse,
    ClinicalConditionItem,
    CrisisTypeItem,
    TaxonomyResponse,
)
from app.schemas.auth import (
    AnonymousAuthRequest,
    GoogleAuthRequest,
    LoginRequest,
    MessageResponse,
    PhoneSendOtpRequest,
    PhoneVerifyRequest,
    RegisterRequest,
    TokenRefreshRequest,
    TokenResponse,
)
from app.schemas.skill import (
    SkillCertificateUploadResponse,
    SkillClaimRequest,
    SkillVerificationListResponse,
    SkillVerificationResponse,
    SkillVerificationReviewRequest,
    TrustScoreUpdateResponse,
)
from app.schemas.user import (
    DeviceRegisterRequest,
    EmergencyContactCreateSchema,
    EmergencyContactSchema,
    EmergencyContactUpdateSchema,
    LanguagePreferencesRequest,
    MedicalIDResponse,
    MedicalIDUpdateRequest,
    PhotoUploadResponse,
    SkillItemSchema,
    UserResponse,
    UserUpdateRequest,
)

__all__ = [
    "AnonymousAuthRequest",
    "ClassificationRequest",
    "ClassificationResponse",
    "ClinicalConditionItem",
    "CrisisTypeItem",
    "DeviceRegisterRequest",
    "EmergencyContactCreateSchema",
    "EmergencyContactSchema",
    "EmergencyContactUpdateSchema",
    "GoogleAuthRequest",
    "LanguagePreferencesRequest",
    "LoginRequest",
    "MedicalIDResponse",
    "MedicalIDUpdateRequest",
    "MessageResponse",
    "PhoneSendOtpRequest",
    "PhoneVerifyRequest",
    "PhotoUploadResponse",
    "RegisterRequest",
    "SkillCertificateUploadResponse",
    "SkillClaimRequest",
    "SkillItemSchema",
    "SkillVerificationListResponse",
    "SkillVerificationResponse",
    "SkillVerificationReviewRequest",
    "TaxonomyResponse",
    "TokenRefreshRequest",
    "TokenResponse",
    "TrustScoreUpdateResponse",
    "UserResponse",
    "UserUpdateRequest",
]
